chore: update flake inputs (Fri Jun  6 08:16:51 UTC 2025)
```console
unpacking 'github:serokell/deploy-rs/6bc76b872374845ba9d645a2f012b764fecd765f' into the Git cache...
unpacking 'github:hercules-ci/flake-parts/49f0870db23e8c1ca0b5259734a02cd9e1e371a1' into the Git cache...
unpacking 'github:nix-community/home-manager/91287a0e9d42570754487b7e38c6697e15a9aab2' into the Git cache...
unpacking 'github:drupol/nix-oracle-db/ed83fc92be4fc718ed2c2e2cdb9854f4f40ddb3e' into the Git cache...
unpacking 'github:nix-community/nixos-generators/ee07ba0d36c38e9915c55d2ac5a8fb0f05f2afcc' into the Git cache...
unpacking 'github:NixOS/nixos-hardware/4602f7e1d3f197b3cb540d5accf5669121629628' into the Git cache...
unpacking 'github:nixos/nixpkgs/c2a03962b8e24e669fb37b7df10e7c79531ff1a4' into the Git cache...
unpacking 'github:NixOS/nixpkgs/743f3402640781235c6ee42d4278a70d4ad03b4b' into the Git cache...
unpacking 'github:nixos/nixpkgs/e4b09e47ace7d87de083786b404bf232eb6c89d8' into the Git cache...
unpacking 'github:nix-community/NUR/e2549db8187bce9e7a410e7ba5e0d4dbfd638351' into the Git cache...
unpacking 'github:numtide/treefmt-nix/a05be418a1af1198ca0f63facb13c985db4cb3c5' into the Git cache...
warning: updating lock file "/home/runner/work/_temp/worktree.P92lABW9yd/flake.lock":
• Updated input 'deploy-rs':
    'github:serokell/deploy-rs/aa07eb05537d4cd025e2310397a6adcedfe72c76?narHash=sha256-3KyjMPUKHkiWhwR91J1YchF6zb6gvckCAY1jOE%2Bne0U%3D' (2024-09-27)
  → 'github:serokell/deploy-rs/6bc76b872374845ba9d645a2f012b764fecd765f?narHash=sha256-hXh76y/wDl15almBcqvjryB50B0BaiXJKk20f314RoE%3D' (2025-06-05)
• Updated input 'deploy-rs/flake-compat':
    'github:edolstra/flake-compat/0f9255e01c2351cc7d116c072cb317785dd33b33?narHash=sha256-kvjfFW7WAETZlt09AgDn1MrtKzP7t90Vf7vypd3OL1U%3D' (2023-10-04)
  → 'github:edolstra/flake-compat/ff81ac966bb2cae68946d5ed5fc4994f96d0ffec?narHash=sha256-NeCCThCEP3eCl2l/%2B27kNNK7QrwZB1IJCrXfrbv5oqU%3D' (2024-12-04)
• Updated input 'deploy-rs/utils':
    'github:numtide/flake-utils/4022d587cbbfd70fe950c1e2083a02621806a725?narHash=sha256-kAuep2h5ajznlPMD9rnQyffWG8EM/C73lejGofXvdM8%3D' (2023-12-04)
  → 'github:numtide/flake-utils/11707dc2f618dd54ca8739b309ec4fc024de578b?narHash=sha256-l0KFg5HjrsfsO/JpG%2Br7fRrqm12kzFHyUHqHCVpMMbI%3D' (2024-11-13)
• Updated input 'flake-parts':
    'github:hercules-ci/flake-parts/c621e8422220273271f52058f618c94e405bb0f5?narHash=sha256-hIshGgKZCgWh6AYJpJmRgFdR3WUbkY04o82X05xqQiY%3D' (2025-04-01)
  → 'github:hercules-ci/flake-parts/49f0870db23e8c1ca0b5259734a02cd9e1e371a1?narHash=sha256-F82%2BgS044J1APL0n4hH50GYdPRv/5JWm34oCJYmVKdE%3D' (2025-06-01)
• Updated input 'home-manager':
    'github:nix-community/home-manager/5675a9686851d9626560052a032c4e14e533c1fa?narHash=sha256-5kvBbLYdp%2Bn7Ftanjcs6Nv%2BUO6sBhelp6MIGJ9nWmjQ%3D' (2025-06-01)
  → 'github:nix-community/home-manager/91287a0e9d42570754487b7e38c6697e15a9aab2?narHash=sha256-bXcEx1aZUNm5hMLVJeuofcOrZyOiapzvQ7K36HYK3YQ%3D' (2025-06-06)
• Updated input 'nixos-hardware':
    'github:NixOS/nixos-hardware/daa628a725ab4948e0e2b795e8fb6f4c3e289a7a?narHash=sha256-pZH4bqbOd8S%2Bsi6UcfjHovWDiWKiIGRNRMpmRWaDIms%3D' (2025-05-30)
  → 'github:NixOS/nixos-hardware/4602f7e1d3f197b3cb540d5accf5669121629628?narHash=sha256-W5GKQHgunda/OP9sbKENBZhMBDNu2QahoIPwnsF6CeM%3D' (2025-06-06)
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/910796cabe436259a29a72e8d3f5e180fc6dfacc?narHash=sha256-StSrWhklmDuXT93yc3GrTlb0cKSS0agTAxMGjLKAsY8%3D' (2025-05-31)
  → 'github:nixos/nixpkgs/c2a03962b8e24e669fb37b7df10e7c79531ff1a4?narHash=sha256-lcZQ8RhsmhsK8u7LIFsJhsLh/pzR9yZ8yqpTzyGdj%2BQ%3D' (2025-06-03)
• Updated input 'nixpkgs-master':
    'github:NixOS/nixpkgs/d8d7795a14435294d0b5f8cb1b8a9d791328a0ab?narHash=sha256-ractU3zRifAqWkUq%2BV6u1F1%2BQpdknTLZMm%2B34ne6CDE%3D' (2025-06-01)
  → 'github:NixOS/nixpkgs/743f3402640781235c6ee42d4278a70d4ad03b4b?narHash=sha256-Ed2vNrygzyaI7iINesUkhy7JMJyY5mvkZXvGcnFp2ec%3D' (2025-06-06)
• Updated input 'nixpkgs-unstable':
    'github:nixos/nixpkgs/59138c7667b7970d205d6a05a8bfa2d78caa3643?narHash=sha256-7gGa49iB9nCnFk4h/g9zwjlQAyjtpgcFkODjcOQS0Es%3D' (2025-05-31)
  → 'github:nixos/nixpkgs/e4b09e47ace7d87de083786b404bf232eb6c89d8?narHash=sha256-RlTsJUvvr8ErjPBsiwrGbbHYW8XbB/oek0Gi78XdWKg%3D' (2025-06-02)
• Updated input 'nur':
    'github:nix-community/NUR/2786e3c51859ba35e77445105ba32d0a8f894a0f?narHash=sha256-8S5G9xO7qoMMO2K85/mZSpFUJzgJJJF3xU5/mHuFJbY%3D' (2025-06-01)
  → 'github:nix-community/NUR/e2549db8187bce9e7a410e7ba5e0d4dbfd638351?narHash=sha256-EpZ5xaH73G0WdF5yMQqinanYQQbHGxU84CTfY6JMEyA%3D' (2025-06-06)
• Updated input 'nur/nixpkgs':
    'github:nixos/nixpkgs/910796cabe436259a29a72e8d3f5e180fc6dfacc?narHash=sha256-StSrWhklmDuXT93yc3GrTlb0cKSS0agTAxMGjLKAsY8%3D' (2025-05-31)
  → 'github:nixos/nixpkgs/c2a03962b8e24e669fb37b7df10e7c79531ff1a4?narHash=sha256-lcZQ8RhsmhsK8u7LIFsJhsLh/pzR9yZ8yqpTzyGdj%2BQ%3D' (2025-06-03)
• Updated input 'treefmt-nix':
    'github:numtide/treefmt-nix/1f3f7b784643d488ba4bf315638b2b0a4c5fb007?narHash=sha256-9YzfeN8CB6SzNPyPm2XjRRqSixDopTapaRsnTpXUEY8%3D' (2025-05-26)
  → 'github:numtide/treefmt-nix/a05be418a1af1198ca0f63facb13c985db4cb3c5?narHash=sha256-eEy8cuS0mZ2j/r/FE0/LYBSBcIs/MKOIVakwHVuqTfk%3D' (2025-06-06)
```
```console

Host: x13
Build failed:
trace: using non-memoized system wasm32-wasi
trace: using non-memoized system wasm32-wasi
warning: download buffer is full; consider increasing the 'download-buffer-size' setting
error: Cannot build '/nix/store/3l0kac1lg582p6zvlpy1ix3nzwv44za6-displaylink-610.zip.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/a10lxg1y9hc5ida4npg2mrmymc8932hl-displaylink-610.zip
       Last 21 log lines:
       >
       > ***
       > In order to install the DisplayLink drivers, you must first
       > comply with DisplayLink's EULA and download the binaries and
       > sources from here:
       >
       > https://www.synaptics.com/products/displaylink-usb-graphics-software-ubuntu-61
       >
       > Once you have downloaded the file, please use the following
       > commands and re-run the installation:
       >
       > mv $PWD/"DisplayLink USB Graphics Software for Ubuntu6.1-EXE.zip" $PWD/displaylink-610.zip
       > nix-prefetch-url file://$PWD/displaylink-610.zip
       >
       > Alternatively, you can use the following command to download the
       > file directly:
       >
       > nix-prefetch-url --name displaylink-610.zip https://www.synaptics.com/sites/default/files/exe_files/2024-10/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.1-EXE.zip
       >
       > ***
       >
       For full logs, run:
         nix log /nix/store/3l0kac1lg582p6zvlpy1ix3nzwv44za6-displaylink-610.zip.drv
error: Cannot build '/nix/store/wv9mq9k010smki8833q5ppp29zawhh2d-displaylink-6.1.0-17.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/0b9mfp2cvgxrh7jkaa86l108w60ci82g-displaylink-6.1.0-17
error: Cannot build '/nix/store/gfxjscalkch1ib77qk34vcdrd18l4wpd-hwdb.bin.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/zkn0hsm3iz1g1zpx99cqdz46gfns00hn-hwdb.bin
error: Cannot build '/nix/store/5z87q6mji4jp8xqsbg82pmkyl4kggax1-udev-rules.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/9abirviz6qkyizf5hjw6m05fvjs9b7if-udev-rules
error: Cannot build '/nix/store/zjmc6mc4fmpa2fbc9jcr8grlrpcjcvif-unit-dlm.service.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/m2aihw42q6w6zp87lwv61rjigvggr41k-unit-dlm.service
error: Cannot build '/nix/store/8kmzsbjw2knyi4ybkdb1w0d62kkwjhwx-X-Restart-Triggers-systemd-udevd.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/h85q1mglqbff182az4phak220wg7nr0n-X-Restart-Triggers-systemd-udevd
error: Cannot build '/nix/store/0i64s9ymcx9aqg97qjsicla9zadz2b9n-etc.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/q6zcqydp0vsv80mfqg90j6hyhikvp76j-etc
error: Cannot build '/nix/store/7qcc82jkl6fkxhv7bd56nnax9m5ckpsn-nixos-system-x13-25.11.20250531.910796c.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/2gn7b768rhck8dcs5yb7dv5ly7301a3b-nixos-system-x13-25.11.20250531.910796c

Host: x13
Build failed:
warning: Git tree '/home/runner/work/_temp/worktree.P92lABW9yd' is dirty
trace: using non-memoized system wasm32-wasi
trace: using non-memoized system wasm32-wasi
error: Cannot build '/nix/store/3l0kac1lg582p6zvlpy1ix3nzwv44za6-displaylink-610.zip.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/a10lxg1y9hc5ida4npg2mrmymc8932hl-displaylink-610.zip
       Last 21 log lines:
       >
       > ***
       > In order to install the DisplayLink drivers, you must first
       > comply with DisplayLink's EULA and download the binaries and
       > sources from here:
       >
       > https://www.synaptics.com/products/displaylink-usb-graphics-software-ubuntu-61
       >
       > Once you have downloaded the file, please use the following
       > commands and re-run the installation:
       >
       > mv $PWD/"DisplayLink USB Graphics Software for Ubuntu6.1-EXE.zip" $PWD/displaylink-610.zip
       > nix-prefetch-url file://$PWD/displaylink-610.zip
       >
       > Alternatively, you can use the following command to download the
       > file directly:
       >
       > nix-prefetch-url --name displaylink-610.zip https://www.synaptics.com/sites/default/files/exe_files/2024-10/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.1-EXE.zip
       >
       > ***
       >
       For full logs, run:
         nix log /nix/store/3l0kac1lg582p6zvlpy1ix3nzwv44za6-displaylink-610.zip.drv
error: Cannot build '/nix/store/wv9mq9k010smki8833q5ppp29zawhh2d-displaylink-6.1.0-17.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/0b9mfp2cvgxrh7jkaa86l108w60ci82g-displaylink-6.1.0-17
error: Cannot build '/nix/store/wxcb23018ynyhx5bdd21l5bh6fq2smnb-hwdb.bin.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/zkn0hsm3iz1g1zpx99cqdz46gfns00hn-hwdb.bin
error: Cannot build '/nix/store/ca41djgnggfi4j806qv7k8myk73qxvp2-udev-rules.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/9abirviz6qkyizf5hjw6m05fvjs9b7if-udev-rules
error: Cannot build '/nix/store/zjmc6mc4fmpa2fbc9jcr8grlrpcjcvif-unit-dlm.service.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/m2aihw42q6w6zp87lwv61rjigvggr41k-unit-dlm.service
error: Cannot build '/nix/store/3hqxvhlv5a920vssb4nkzq4lhfaharcw-X-Restart-Triggers-systemd-udevd.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/h85q1mglqbff182az4phak220wg7nr0n-X-Restart-Triggers-systemd-udevd
error: Cannot build '/nix/store/mn9qxsbd841i9111zaq1cln2bi909w5g-etc.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/lrlp8jbp9z5agvjizkidrcifab9gsspy-etc
warning: download buffer is full; consider increasing the 'download-buffer-size' setting
error: Cannot build '/nix/store/drjwl9cw8ay7yfd7012sjryw0mc7zb2m-nixos-system-x13-25.11.20250603.c2a0396.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/fh7q2ragjhbvj9dbjzlj459gia4grrvl-nixos-system-x13-25.11.20250603.c2a0396

Host: x13
Diff failed:
Path does not exist: x13.current

Host: x260
<<< x260.current
>>> x260.next
Version changes:
[U.]  #1  bootspec           1.0.0 -> 1.0.1
[C*]  #2  dconf              0.40.0, 0.40.0_fish-completions x2, 0.40.0-lib x2 -> 0.40.0, 0.40.0_fish-completions, 0.40.0-lib x2
[U.]  #3  gh-dash            4.15.0, 4.15.0-fish-completions -> 4.16.0, 4.16.0-fish-completions
[U.]  #4  libkate            0.4.1 -> 0.4.3
[U*]  #5  netbird            0.45.1 x2, 0.45.1-fish-completions, 0.45.1-wrapper-netbird -> 0.45.2 x2, 0.45.2-fish-completions, 0.45.2-wrapper-netbird
[U.]  #6  nixos-system-x260  25.11.20250531.910796c -> 25.11.20250603.c2a0396
[U.]  #7  ruff               0.11.11 -> 0.11.12
[U.]  #8  winbox             4.0beta20, 4.0beta20-fish-completions -> 4.0beta21, 4.0beta21-fish-completions
Added packages:
[A.]  #1  1zw47fx5h4x65n914j4b9iz0j3v17aw0-source  <none>
[A.]  #2  initrd-shells                            <none>
[A.]  #3  zed-user-keymaps                         <none>
Removed packages:
[R.]  #1  dax78flrvcdir20swzlcm64va09nh5x8-source  <none>
Closure size: 2281 -> 2282 (85 paths added, 84 paths removed, delta +1, disk usage -1.4MiB).

Host: x280
<<< x280.current
>>> x280.next
Version changes:
[U.]  #1  bootspec           1.0.0 -> 1.0.1
[C*]  #2  dconf              0.40.0, 0.40.0_fish-completions x2, 0.40.0-lib x2 -> 0.40.0, 0.40.0_fish-completions, 0.40.0-lib x2
[U.]  #3  gh-dash            4.15.0, 4.15.0-fish-completions -> 4.16.0, 4.16.0-fish-completions
[U.]  #4  libkate            0.4.1 -> 0.4.3
[U*]  #5  netbird            0.45.1 x2, 0.45.1-fish-completions, 0.45.1-wrapper-netbird -> 0.45.2 x2, 0.45.2-fish-completions, 0.45.2-wrapper-netbird
[U.]  #6  nixos-system-x280  25.11.20250531.910796c -> 25.11.20250603.c2a0396
[U.]  #7  ruff               0.11.11 -> 0.11.12
[U.]  #8  winbox             4.0beta20, 4.0beta20-fish-completions -> 4.0beta21, 4.0beta21-fish-completions
Added packages:
[A.]  #1  1zw47fx5h4x65n914j4b9iz0j3v17aw0-source  <none>
[A.]  #2  initrd-shells                            <none>
[A.]  #3  zed-user-keymaps                         <none>
Removed packages:
[R.]  #1  dax78flrvcdir20swzlcm64va09nh5x8-source  <none>
Closure size: 2264 -> 2265 (85 paths added, 84 paths removed, delta +1, disk usage -1.4MiB).

Host: xeonixos
<<< xeonixos.current
>>> xeonixos.next
Version changes:
[C*]  #1  dconf                  0.40.0, 0.40.0_fish-completions x2, 0.40.0-lib -> 0.40.0, 0.40.0_fish-completions, 0.40.0-lib
[U.]  #2  gh-dash                4.15.0, 4.15.0-fish-completions -> 4.16.0, 4.16.0-fish-completions
[U.]  #3  libkate                0.4.1 -> 0.4.3
[U*]  #4  netbird                0.45.1 x2, 0.45.1-fish-completions, 0.45.1-wrapper-netbird -> 0.45.2 x2, 0.45.2-fish-completions, 0.45.2-wrapper-netbird
[U.]  #5  nixos-system-xeonixos  25.11.20250531.910796c -> 25.11.20250603.c2a0396
[U.]  #6  ruff                   0.11.11 -> 0.11.12
[U.]  #7  winbox                 4.0beta20, 4.0beta20-fish-completions -> 4.0beta21, 4.0beta21-fish-completions
Added packages:
[A.]  #1  1zw47fx5h4x65n914j4b9iz0j3v17aw0-source  <none>
[A.]  #2  initrd-nixos.conf                        <none>
[A.]  #3  zed-user-keymaps                         <none>
Removed packages:
[R.]  #1  dax78flrvcdir20swzlcm64va09nh5x8-source  <none>
[R.]  #2  unit-initrd.target                       <none>
Closure size: 2081 -> 2081 (86 paths added, 86 paths removed, delta +0, disk usage -1.4MiB).

```